# Generated by Django 2.2.1 on 2019-05-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_hleba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hleb',
            name='img',
            field=models.FileField(upload_to='./static/'),
        ),
    ]
