# Generated by Django 2.2.1 on 2019-05-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20190514_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hleb',
            name='img',
            field=models.FileField(upload_to='./main/static/'),
        ),
    ]
