# Generated by Django 2.2.1 on 2019-05-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20190515_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hleb',
            name='img',
            field=models.FileField(upload_to='./static/'),
        ),
    ]
