# Generated by Django 2.2.1 on 2019-05-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20190516_0954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hleba',
        ),
    ]
