# Generated by Django 2.2.1 on 2019-06-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_proba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hleba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('kratk', models.CharField(max_length=80)),
                ('button', models.CharField(max_length=12)),
                ('img', models.FileField(upload_to='./static/')),
            ],
        ),
        migrations.AlterField(
            model_name='hleb',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
